routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['register' => false]);

Route::view('/', 'layouts.welcome')->name('index');
Route::get('pages', 'HomeController@showPages');
Route::post('page', 'HomeController@storePage')->name('page.store');
Route::post('token', 'HomeController@storeToken');
Route::resource('notifications', 'NotificationController');

Route::middleware('auth', 'admin')->group(function () {
    Route::prefix('a')->group(function () {
        Route::get('home', 'Administrator\AdminController@home')->name('admin.home');
        Route::get('file-manager', 'Administrator\AdminController@fileManager')->name('admin.fm');
        Route::get('profile', 'Administrator\AdminController@profile')->name('admin.profile');
        Route::get('reports', 'Administrator\ReportController@reports')->name('admin.reports');
        Route::post('reports/courses', 'Administrator\ReportController@courses')->name('admin.courses');
        Route::post('reports/department', 'Administrator\ReportController@department')->name('admin.dept');
        Route::post('reports/download', 'Administrator\ReportController@download')->name('admin.download');
        Route::post('reports/generate', 'Administrator\ReportController@generate')->name('admin.generate');
        Route::post('reports/one', 'Administrator\ReportController@one')->name('admin.one');
        Route::post('reports/two', 'Administrator\ReportController@two')->name('admin.two');
        Route::post('departments/fetch', 'Administrator\DepartmentController@fetch')->name('dept.fetch');
        Route::post('linkedin/parse', 'Administrator\LinkedInController@parse')->name('in.parse');
        Route::post('linkedin/upload', 'Administrator\LinkedInController@upload')->name('in.upload');
        Route::resources([
            'users' => 'Administrator\UserController',
            'accounts' => 'Administrator\AccountController',
            'linkedin' => 'Administrator\LinkedInController',
            'schools' => 'Administrator\SchoolController',
            'departments' => 'Administrator\DepartmentController',
        ]);
    });
});

Route::middleware('auth', 'dept')->group(function () {
    Route::prefix('d')->group(function () {
        Route::get('home', 'Department\DepartmentController@home')->name('dept.home');
        Route::get('file-manager', 'Department\DepartmentController@fileManager')->name('dept.fm');
        Route::get('profile', 'Department\DepartmentController@profile')->name('dept.profile');
        Route::get('reports', 'Department\ReportController@reports')->name('dept.reports');
        Route::post('reports/download', 'Department\ReportController@download')->name('dept.download');
        Route::post('reports/generate', 'Department\ReportController@generate')->name('dept.generate');
        Route::post('graduates/confirm', 'Department\GraduateController@confirm')->name('g.confirm');
        Route::post('graduates/preview', 'Department\GraduateController@preview')->name('g.preview');
        Route::post('graduates/upload', 'Department\GraduateController@upload')->name('g.upload');
        Route::resources([
            'graduates' => 'Department\GraduateController',
            'courses' => 'Department\CourseController',
            'jobs' => 'Department\OccupationController',
            'points' => 'Department\PointController',
            'rewards' => 'Department\RewardController',
            'requests' => 'Department\VerificationController'
        ]);
    });
});

app/Models/Department.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Department extends Model
{
    protected $guarded = [];
    public $incrementing = false;
    public $keyType = 'string';

    public function admins()
    {
        return $this->belongsToMany(Admin::class, 'admin_department', 'dept_id', 'admin_id')->withTimestamps();
    }

    public function courses()
    {
        return $this->belongsToMany(Course::class, 'department_course', 'dept_id', 'course_id')->withTimestamps();
    }

    public function schools()
    {
        return $this->belongsToMany(School::class, 'school_department', 'dept_id', 'school_id')->withTimestamps();
    }

    public function getImageAttribute()
    {
        if ($this->logo != null) {
            return Str::of(rawurldecode($this->logo))->replace('+', ' ')->__toString();
        }

        return asset('img/app/logo.png');
    }
}

app/Models/Graduate.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Graduate extends Model
{
    protected $guarded = [];
    protected $primaryKey = 'graduate_id';
    public $incrementing = false;
    public $keyType = 'string';

    public function contacts()
    {
        return $this->hasMany(Contact::class, 'graduate_id');
    }

    public function academic()
    {
        return $this->hasOne(Academic::class, 'graduate_id');
    }

    public function employments()
    {
        return $this->hasMany(Employment::class, 'graduate_id');
    }

    public function confirmed()
    {
        return $this->hasMany(Confirmed::class, 'graduate_id');
    }

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function person()
    {
        return $this->belongsTo(Person::class, 'person_id');
    }

    public function users()
    {
        return $this->belongsToMany(User::class, 'user_graduate', 'graduate_id', 'user_id')
            ->as('respondent')->withPivot('response_id')->withTimestamps()->latest();
    }

    public function responses()
    {
        return $this->belongsToMany(Response::class, 'user_graduate', 'graduate_id', 'response_id')
            ->as('respondent')->withPivot('user_id')->withTimestamps()->latest();
    }

    public function getFullNameAttribute()
    {
        return "{$this->person->first_name} {$this->person->middle_name} {$this->person->last_name}";
    }

    public function getNameAttribute()
    {
        $middleName = Str::substr($this->person->middle_name, 0, 1);

        return "{$this->person->first_name} {$middleName} {$this->person->last_name}";
    }

    public function getCourseAttribute()
    {
        return $this->academic->course->title;
    }

    public function getMajorAttribute()
    {
        return $this->academic->course->major;
    }

    public function getDegreeProgramAttribute()
    {
        return $this->academic->course->major == 'None' ? $this->academic->course->title : "{$this->academic->course->title} - {$this->academic->course->major}";
    }

    public function getDateGraduatedAttribute()
    {
        return "{$this->academic->month} {$this->academic->day}, {$this->academic->year}";
    }

    public function getAddressAttribute()
    {
        return $this->contacts->first()->address;
    }

    public function getContactAttribute()
    {
        return $this->contacts->first()->contact_number ?? 'None';
    }

    public function getEmploymentStatusAttribute()
    {
        return $this->confirmed->first()->status;
    }

    public function getCompanyNameAttribute()
    {
        return $this->confirmed->first()->employment->company->name;
    }

    public function getCompanyAddressAttribute()
    {
        return $this->confirmed->first()->employment->company->address;
    }

    public function getCompanyContactAttribute()
    {
        return $this->confirmed->first()->employment->company->contact_number;
    }

    public function getJobPositionAttribute()
    {
        return $this->confirmed->first()->employment->job_position;
    }

    public function getDateEmployedAttribute()
    {
        return $this->confirmed->first()->employment->date_employed;
    }

    public function getRemarksAttribute()
    {
        return $this->confirmed->first()->remarks;
    }

    public function getStatusAttribute()
    {
        return $this->confirmed->first() == null ? 'Open' : 'Closed';
    }

    public function getImageAttribute()
    {
        $defaultImage = $this->person->gender == 'Male' ? 'default_avatar_m.png' : 'default_avatar_f.png';
        $imagePath = Str::of(rawurldecode($this->image_uri))->replace('+', ' ')->__toString();

        if ($this->image_uri != null) {
            return $imagePath;
        }

        return asset("img/app/{$defaultImage}");
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Laravel\Passport\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, Notifiable;

    protected $guarded = [];
    protected $primaryKey = 'user_id';
    public $incrementing = false;
    public $keyType = 'string';

    public function admin()
    {
        return $this->hasOne(Admin::class, 'user_id');
    }

    public function contacts()
    {
        return $this->hasMany(Contact::class, 'user_id')->latest();
    }

    public function graduate()
    {
        return $this->hasOne(Graduate::class, 'user_id');
    }

    public function providerAccounts()
    {
        return $this->hasMany(ProviderAccount::class, 'user_id');
    }

    public function twitterFriendIds()
    {
        return $this->hasMany(TwitterFriendId::class, 'user_id');
    }

    public function preference()
    {
        return $this->hasOne(Preference::class, 'user_id');
    }

    public function achievement()
    {
        return $this->hasOne(Achievement::class, 'user_id');
    }

    public function person()
    {
        return $this->belongsTo(Person::class, 'person_id');
    }

    public function employments()
    {
        return $this->belongsToMany(Employment::class, 'user_employment', 'user_id', 'employment_id')->withTimestamps();
    }

    public function graduates()
    {
        return $this->belongsToMany(Graduate::class, 'user_graduate', 'user_id', 'graduate_id')
            ->as('respondent')->withPivot('response_id')->orderByDesc('user_graduate.updated_at')->withTimestamps();
    }

    public function responses()
    {
        return $this->belongsToMany(Response::class, 'user_graduate', 'user_id', 'response_id')
            ->as('respondent')->withPivot('graduate_id')->orderByDesc('user_graduate.updated_at')->withTimestamps();
    }

    public function rewards()
    {
        return $this->belongsToMany(Reward::class, 'user_reward', 'user_id', 'reward_id')
            ->withPivot('id', 'status')->orderByDesc('user_reward.updated_at')->withTimestamps();
    }

    public function getFullNameAttribute()
    {
        return "{$this->person->first_name} {$this->person->middle_name} {$this->person->last_name}";
    }

    public function getDepartmentAttribute()
    {
        return $this->graduate->academic->department;
    }

    public function getSchoolAttribute()
    {
        return $this->graduate->academic->school;
    }

    public function getImageAttribute()
    {
        $defaultImage = $this->person->gender == 'Male' ? 'default_avatar_m.png' : 'default_avatar_f.png';
        $imagePath = rawurldecode($this->image_uri);

        if ($this->image_uri != null) {
            return $imagePath;
        }

        return asset("img/app/{$defaultImage}");
    }

    public function routeNotificationForFcm($notification)
    {
        return $this->device_token;
    }
}

app/Http/Controllers/Administrator/DepartmentController.php
<?php

namespace App\Http\Controllers\Administrator;

use App\Http\Controllers\Controller;
use App\Http\Requests\StoreDepartmentRequest;
use App\Models\Department;
use App\Models\School;
use App\Traits\StaticTrait;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use Intervention\Image\Facades\Image;

class DepartmentController extends Controller
{
    use StaticTrait;

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware(['auth', 'admin']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $schools = School::orderBy('name')->get();
        $depts = Department::orderBy('name')->paginate(15);
        $page = request()->page;

        return view('administrator.department', compact('depts', 'schools', 'page'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreDepartmentRequest $request)
    {
        $imagePath = null; $data = $request->validated();
        $school = School::where('name', $data['school'])->first();
        $dept = Department::whereHas('schools', fn ($query) =>
            $query->where('name', $this->capitalize($school->name))
        )->where('name', $this->capitalize($data['dept']))->first();

        if ($request->hasFile('logo')) {
            $file = $request->file('logo');
            $directory = "files/shares/logos/department/{$school->name}";

            if (Storage::makeDirectory("public/{$directory}")) {
                $imagePath = $file->storeAs($directory, $file->getClientOriginalName(), 'public');
                $image = Image::make(public_path("storage/{$imagePath}"));
                $image->fit(130, 130); $image->save();
                $imagePath = Storage::url($imagePath);
            }
        }

        if ($dept && $request->btnDept == 'added') {
            return back()->withErrors("Department name has already been taken.");
        }

        $department = Department::updateOrCreate([
            'id' => $request->department ?? Str::random()
        ], [
            'name' => $this->capitalize($data['dept']),
            'logo' => $imagePath ?? Department::find($request->department)->logo ?? null
        ]);

        $department->schools()->syncWithoutDetaching($school->id);

        return back()->with('success', "Department {$request->btnDept} successfully.");
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $dept = Department::with('schools')->find($id);

        return response()->json(compact('dept'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $dept = Department::with('schools')->find($id);

        return response()->json(compact('dept'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = Str::of($id)->explode('+');
        $department = Department::find($data[0]);

        if ($department) {
            $department->schools()->detach($data[1]);
        }

        return back()->with('success', "Department removed succesfully.");
    }

    public function fetch(Request $request)
    {
        $school = School::where('name', $request->get('value'))->first();
        $data = $school->departments()->get();
        $option = "<option value='' selected>- Select Department -</option>";

        foreach ($data as $row) {
            $option .= "<option value='{$row->name}'>{$row->name}</option>";
        }

        return $option;
    }
}

app/Http/Controllers/Department/DepartmentController.php
<?php

namespace App\Http\Controllers\Department;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Support\Facades\Auth;

class DepartmentController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware(['auth', 'dept']);
    }

    public function home()
    {
        return view('layouts.home');
    }

    public function fileManager()
    {
        return view('layouts.file_manager');
    }

    public function profile()
    {
        $user = User::find(Auth::user()->user_id);

        return view('layouts.profile', compact('user'));
    }
}

resources/views/department/courses.blade.php
@extends('layouts.home')

@section('title', 'Degree Programs')

@section('header')
<i class="book reader teal icon"></i> @yield('title')
@endsection

@section('button')
<button class="ui right floated teal button add-course">
    <i class="plus icon"></i> {{ __('Add Degree Program') }}
</button>
@endsection

@section('main')
@if ($courses->isNotEmpty())
<x-course.list :courses="$courses" />
@else
<div class="ui placeholder basic segment">
    <div class="ui icon header">
        <i class="exclamation circle teal icon"></i>
        {{ __('Click the \'Add Degree Program\' button to display it here.') }}
    </div>
</div>
@endif
@endsection

@section('modal')
<x-course.add :courses="$courses" />
<x-course.delete />
@endsection

resources/views/department/download.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html" charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ __('Download PDF') }}</title>
    <link rel="icon" href="{{ asset('images/favicon.png') }}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <style>
        @font-face {
            font-family: 'Product Sans';
            font-style: normal;
            font-weight: normal;
            src: url({{ asset('fonts/Product-Sans.ttf') }}) format('truetype');
        }
        body {
            font-family: 'Product Sans', Verdana, Geneva, Tahoma, sans-serif;
            font-size: 14px;
        }
    </style>
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col">
                <div class="text-center">
                    <h3 class="text-uppercase font-weight-bold">{{ __("College of {$department} Graduate Tracer") }}</h3>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <div class="text-center">
                    <h4 class="font-weight-normal">{{ __("{$term->first()}") }}</h4>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <div class="text-center py-4">
                    <h6 class="text-uppercase font-weight-bold">{{ __("{$course->title}") }}</h6>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <table class="table table-sm table-bordered">
                    <thead>
                        <tr class="text-center">
                            <th class="align-middle" style="width: 15%">{{ __('Name') }}</th>
                            <th class="align-middle" style="width: 20%">{{ __('Address') }}</th>
                            <th class="align-middle" style="width: 10%">{{ __('Contact No.') }}</th>
                            <th class="align-middle" style="width: 10%">{{ __('Company') }}</th>
                            <th class="align-middle" style="width: 15%">{{ __('Company Address') }}</th>
                            <th class="align-middle" style="width: 10%">{{ __('Company Contact No.') }}</th>
                            <th class="align-middle" style="width: 10%">{{ __('Position/ Designation') }}</th>
                            <th class="align-middle" style="width: 10%">{{ __('Remarks') }}</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($employed as $item)
                        <tr class="text-center">
                            <td class="align-middle">{{ $item->full_name }}</td>
                            <td class="align-middle">{{ $item->address }}</td>
                            <td class="align-middle">{{ $item->contact }}</td>
                            <td class="align-middle">{{ $item->company_name }}</td>
                            <td class="align-middle">{{ $item->company_address }}</td>
                            <td class="align-middle">{{ $item->company_contact }}</td>
                            <td class="align-middle">{{ $item->job_position }}</td>
                            <td class="align-middle">{{ $item->remarks }}</td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
        <div class="row my-5">
            <div class="col-5">
                <table class="table table-sm table-bordered">
                    <tbody>
                        <tr>
                            <td class="align-middle">{{ __('Total No. of Graduates') }}</td>
                            <td class="align-middle text-center">{{ $confirmed->count() }}</td>
                            <td class="align-middle text-center">{{ __('100%') }}</td>
                        </tr>
                        <tr>
                            <td class="align-middle">{{ __('Employed') }}</td>
                            <td class="align-middle text-center">{{ $employed->count() }}</td>
                            <td class="align-middle text-center">{{ round($employed->count() / $confirmed->count() * 100) . "%" }}</td>
                        </tr>
                        <tr>
                            <td class="align-middle">{{ __('Unemployed') }}</td>
                            <td class="align-middle text-center">{{ $confirmed->count() - $employed->count() }}</td>
                            <td class="align-middle text-center">{{ round(($confirmed->count() - $employed->count()) / $confirmed->count() * 100) . "%" }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</body>
</html>

resources/views/department/graduate.blade.php
@extends('layouts.home')

@section('title', "{$graduate->name}")

@section('header')
<i class="user graduate teal icon"></i>{{ __("Graduate Details - {$graduate->full_name}") }}
@endsection

@section('button')
@if ($graduate->confirmed->isEmpty())
<button class="ui right floated teal button confirm-graduate" role="button">
    <i class="check icon"></i> {{ __('Confirm Graduate') }}
</button>
@endif
@endsection

@section('main')
<div class="ui basic segment">
    <div class="ui breadcrumb">
        <a href="{{ route('graduates.index') }}" class="section">{{ __('Graduate List') }}</a>
        <i class="right angle icon divider"></i>
        <div class="active section">{{ __('Graduate Details') }}</div>
    </div>
</div>
<div class="ui basic segment">
    <div class="ui equal width grid">
        <div class="two wide column">
            <img src="{{ $graduate->image }}" class="ui centered tiny circular image">
        </div>
        <div class="left floated column">
            <h2 class="ui teal header">{{ $graduate->full_name }}
                <div class="ui {{ $graduate->status == "Open" ? 'green' : 'red' }} label">{{ $graduate->status }}</div>
            </h2>
            <div><span class="ui teal text">{{ __('Address:') }}</span> {{ __("{$graduate->address}") }}</div>
            <div><span class="ui teal text">{{ __('Degree Program:') }}</span> {{ __("{$graduate->degree_program}") }}</div>
            <div><span class="ui teal text">{{ __('Date Graduated:') }}</span> {{ __("{$graduate->date_graduated}") }}</div>
            <div><span class="ui teal text">{{ __('Contact No.:') }}</span> {{ __("{$graduate->contact}") }}</div>
            <div>
                <button class="ui green tertiary button edit-graduate">
                    <i class="pen icon"></i> {{ __('Edit') }}
                </button>
                <button class="ui red tertiary button mark-graduate">
                    <i class="trash icon"></i> {{ __('Remove') }}
                </button>
            </div>
        </div>
        <div class="column">
            <div class="ui teal header">{{ __('Employment details') }}</div>
            @if ($graduate->confirmed->isNotEmpty())
            <div><span class="ui teal text">{{ __('Employment Status:') }}</span> {{ __("{$graduate->employment_status}") }}</div>
            @if ($graduate->employment_status == 'Employed')
            <div><span class="ui teal text">{{ __('Company & Address:') }}</span> {{ __("{$graduate->company_name}, {$graduate->company_address}") }}</div>
            <div><span class="ui teal text">{{ __('Position/Designation:') }}</span> {{ __("{$graduate->job_position}") }}</div>
            <div><span class="ui teal text">{{ __('Date Employed:') }}</span> {{ __("{$graduate->date_employed}") }}</div>
            @endif
            <div><span class="ui teal text">{{ __('Remarks:') }}</span> {{ __("{$graduate->remarks}") }}</div>
            <div>
                <button class="ui green tertiary button edit-employment">
                    <i class="pen icon"></i> {{ __('Edit') }}
                </button>
            </div>
            @else
            <div class="ui small yellow message">
                {{ __("Crowdsourcing of employment data is on-going, awaiting for the graduate's confirmation. To confirm, just click the 'Confirm Graduate' button.") }}
            </div>
            @endif
        </div>
    </div>
</div>
@if ($responses->isNotEmpty())
<div class="row">
    <div class="column">
        <div class="ui top attached tabular menu">
            <a class="item active" data-tab="first">{{ __('Dashboard') }}</a>
            <a class="item" data-tab="second">{{ __('Data Table') }}</a>
        </div>
        <div class="ui bottom attached tab segment active" data-tab="first">
            <div class="ui equal width stackable grid container">
                <div class="column">
                    <div class="ui padded raised teal segment">
                        <div class="ui center aligned dividing header">
                            {{ __("Most Frequent Answers based on {$responses->count()} Responses") }}
                            <i class="question circle outline teal small icon link" data-content="Responses that have the highest frequency of answers per category."></i>
                        </div>
                        <div class="ui three small statistics">
                            @foreach ($results as $key => $value)
                            @if ($loop->first)
                            <div class="teal statistic">
                                <div class="value">{{ __("{$value}%") }}</div>
                                <div class="label">{{ Str::of($key)->explode('+')[0] }}</div>
                                <div class="label">{{ Str::of($key)->explode('+')[1] }}</div>
                            </div>
                            @else
                            <div class="teal statistic">
                                <div class="value">{{ __("{$value}%") }}</div>
                                <div class="label">{{ $key }}</div>
                            </div>
                            @endif
                            @endforeach
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="eight wide column">
                        <div class="ui raised padded teal segment">
                            <div class="ui center aligned dividing header">
                                {{ __('Companies answered by Respondents') }}
                            </div>
                            <div id="companies" style="height: 50vh"></div>
                        </div>
                    </div>
                    <div class="eight wide column">
                        <div class="ui raised padded teal segment">
                            <div class="ui center aligned dividing header">
                                {{ __("Respondents with relation to {$graduate->person->first_name}") }}
                            </div>
                            <div id="remarks" style="height: 50vh"></div>
                        </div>
                    </div>
                </div>
                <div class="centered row">
                    <div class="column">
                        <div class="ui raised padded teal segment">
                            <div class="ui center aligned dividing header">
                                {{ __('Job Positions answered by Respondents') }}
                            </div>
                            <div id="positions" style="height: 50vh"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="ui bottom attached tab segment" data-tab="second">
            <table class="ui unstackable selectable celled compact teal table" id="responses" data-page-length="10">
                <thead>
                    <tr class="center aligned">
                        <th>{{ __('Response ID') }}</th>
                        <th>{{ __('Company Name') }}</th>
                        <th>{{ __('Company Address') }}</th>
                        <th>{{ __('Job Position') }}</th>
                        <th>{{ __('Relation') }}</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($responses as $response)
                    <tr class="center aligned">
                        <td>{{ $response->response_id }}</td>
                        <td>{{ $response->company->name }}</td>
                        <td>{{ $response->company->address }}</td>
                        <td>{{ $response->job_position }}</td>
                        <td>{{ $response->remarks }}</td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@else
<div class="ui raised placeholder basic teal segment">
    <div class="ui icon header">
        <i class="exclamation circle teal icon"></i>
        {{ __('No responses yet.') }}
    </div>
</div>
@endif
@endsection

@section('modal')
<x-graduate.add :courses="$courses" />
@if ($responses->isNotEmpty())
<x-graduate.confirm :graduate="$graduate" :responses="$responses" :results="$results" />
@else
<x-graduate.confirm :graduate="$graduate" :responses="$responses" />
@endif
<x-graduate.delete />
@endsection

@section('scripts')
@if ($responses->isNotEmpty())
<script src="{{ asset('js/responses.chart.js') }}" crossorigin="anonymous"></script>
@endif
@endsection